[package]
name = "csv"
version = "0.1.0"
authors = ["labocho <labocho@penguinlab.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "csv"
path = "src/csv.rs"

[dependencies]
csv = "*"
